/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#570000",
        "primary-container": "#800000",
        "on-primary": "#ffffff",
        "on-primary-container": "#ff8371",
        "primary-fixed": "#ffdad4",
        "primary-fixed-dim": "#ffb4a8",
        "on-primary-fixed": "#410000",
        "on-primary-fixed-variant": "#8f0f07",
        secondary: "#5f5e5e",
        "secondary-container": "#e5e2e1",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#656464",
        "secondary-fixed": "#e5e2e1",
        "secondary-fixed-dim": "#c9c6c5",
        "on-secondary-fixed": "#1c1b1b",
        "on-secondary-fixed-variant": "#474646",
        tertiary: "#00137f",
        "tertiary-container": "#0021b9",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#94a0ff",
        "tertiary-fixed": "#dfe0ff",
        "tertiary-fixed-dim": "#bcc2ff",
        "on-tertiary-fixed": "#000c61",
        "on-tertiary-fixed-variant": "#1830c2",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        background: "#fff8f6",
        "on-background": "#261816",
        surface: "#fff8f6",
        "surface-dim": "#eed4d0",
        "surface-bright": "#fff8f6",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fff0ee",
        "surface-container": "#ffe9e6",
        "surface-container-high": "#fde2de",
        "surface-container-highest": "#f7ddd8",
        "on-surface": "#261816",
        "on-surface-variant": "#5a413d",
        "surface-variant": "#f7ddd8",
        "surface-tint": "#b22b1d",
        outline: "#8e706c",
        "outline-variant": "#e2bfb9",
        "inverse-surface": "#3d2d2a",
        "inverse-on-surface": "#ffedea",
        "inverse-primary": "#ffb4a8",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "12px",
        md: "24px",
        lg: "40px",
        xl: "64px",
        gutter: "24px",
        "container-max": "1200px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Poppins", "sans-serif"],
        "headline-md": ["Poppins", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Poppins", "sans-serif"],
        "headline-sm": ["Poppins", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Poppins", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Poppins", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "1", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      maxWidth: {
        "container-max": "1200px",
      },
      animation: {
        "fade-in": "fadeIn 0.3s ease-out",
        "slide-in": "slideIn 0.3s ease-out",
        "slide-up": "slideUp 0.4s ease-out",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideIn: {
          "0%": { transform: "translateX(-10px)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
        slideUp: {
          "0%": { transform: "translateY(20px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
      },
    },
  },
  plugins: [],
};
